name: Release

on:
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
    uses: unpins/action-build/.github/workflows/release.yml@main
    secrets: inherit
