name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: write
    uses: unpins/action-build/.github/workflows/build.yml@main
    secrets: inherit
